name: plugin_helper
description: Plugin for boilerplate mobile
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^8.1.0
  shared_preferences: ^2.0.18
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0
  dio: ^5.0.3
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  firebase_messaging: ^14.3.0
  firebase_analytics: ^10.1.6
  firebase_core: ^2.8.0
  firebase_dynamic_links: ^5.0.17
  firebase_crashlytics: ^3.0.17
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.7
  file_picker: ^5.2.6
  url_launcher: ^6.1.10
  http: ^0.13.5
  new_version_plus: ^0.0.9
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  pin_code_fields: ^7.4.0
  mime_type: ^1.0.0
  meta: ^1.8.0
  libphonenumber: ^2.0.2
  equatable: ^2.0.5
  collection: ^1.17.0
  image: ^4.0.15
  flutter_svg: ^2.0.4
  photo_view: ^0.14.0
  path: ^1.8.2
  overlay_support: ^2.1.0
  share_plus: ^6.3.1
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.tharo.helper.plugin_helper
        pluginClass: PluginHelperPlugin
      ios:
        pluginClass: PluginHelperPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/flags/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
