name: plugin_helper
description: A new flutter plugin project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.3
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  dio: ^4.0.6
  path_provider: ^2.0.9
  permission_handler: ^10.1.0
  firebase_messaging: ^11.2.13
  firebase_analytics: ^9.1.5
  firebase_core: ^1.14.1
  firebase_dynamic_links: ^2.0.6
  flutter_local_notifications: ^9.4.0
  firebase_crashlytics: ^2.6.2
  image_picker: ^0.8.5
  file_picker: ^4.5.1
  url_launcher: ^6.0.20
  new_version:
    git:
      url: https://github.com/timtraversy/new_version.git
      ref: master
  cached_network_image: ^3.2.0
  pull_to_refresh: ^2.0.0
  pin_code_fields: ^7.4.0
  mime_type: ^1.0.0
  connectivity_plus: ^2.3.5
  meta: ^1.3.0
  libphonenumber: ^2.0.2
  equatable: ^2.0.3
  collection: ^1.15.0
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git
  image: ^3.1.3
  flutter_svg: ^1.0.3
  photo_view: ^0.14.0
  overlay_support: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.tharo.helper.plugin_helper
        pluginClass: PluginHelperPlugin
      ios:
        pluginClass: PluginHelperPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/flags/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
